In [37]:
import math

class Circle:
    def __init__(self, r):
        self.radius = r
    def get_radius(self):
        return self.radius
    def getArea(self):
        return math.pi * self.radius ** 2
    def __le__(self, other):
        return self.radius <= other.radius

In [45]:
my_circle = Circle(5.)

In [46]:
my_circle.get_radius()

5.0

In [47]:
my_circle.getArea()

78.53981633974483

# 연산자 오버로딩 아래 한줄

In [48]:
[2,3]+[5,2]

[2, 3, 5, 2]

In [49]:
c1 = Circle(5.5)
c2 = Circle(2.3)
c1 <= c2

False

# 0929, NumPy 실습

In [2]:
import numpy as np

In [10]:
a = np.array([2,6,3,7,8.])

In [11]:
a

array([2., 6., 3., 7., 8.])

In [12]:
print(a)

[2. 6. 3. 7. 8.]


In [13]:
type(a)

numpy.ndarray

ndarray

NumPy에서 가장 강력한 무기로 칭송받고 있는 N차원의 배열 객체.

ndarray는 기존 파이썬과는 다르게 오직 같은 종류의 데이터만을 배열에 담을 수 있다.

x.nidm : 몇차원 배열인지 알려줌

In [14]:
a.ndim

1

몇행 몇열 인지 알려줌

In [15]:
a.shape

(5,)

In [16]:
a.dtype

dtype('float64')

In [20]:
b = np.array([[1,2,3],[4,5,6]])

In [21]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
b.ndim

2

In [23]:
b.shape

(2, 3)

In [24]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [25]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [29]:
np.full((2,3),3.14159)

array([[3.14159, 3.14159, 3.14159],
       [3.14159, 3.14159, 3.14159]])

In [31]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [33]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [28]:
np.random.random()

0.30233257263183977

In [50]:
np.random.seed(1)

In [51]:
np.random.random()

0.417022004702574

In [52]:
np.random.random((3,3))

array([[7.20324493e-01, 1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02, 1.86260211e-01],
       [3.45560727e-01, 3.96767474e-01, 5.38816734e-01]])

In [53]:
np.random.normal(0,1,(2,3))

array([[ 1.74481176, -0.7612069 ,  0.3190391 ],
       [-0.24937038,  1.46210794, -2.06014071]])

In [60]:
np.random.randint(1, 7, 10)

array([2, 6, 4, 1, 1, 6, 6, 5, 6, 3])

In [47]:
x = np.array([5,2,9,3,7]) 

In [48]:
y = np.array([[2,4,6],[1,3,5]])

In [49]:
x

array([5, 2, 9, 3, 7])

In [50]:
y

array([[2, 4, 6],
       [1, 3, 5]])

In [51]:
x[2]

9

In [54]:
y[1,1]

3

In [55]:
x[1:4]

array([2, 9, 3])

In [56]:
x[1:]

array([2, 9, 3, 7])

In [57]:
x[:2]

array([5, 2])

In [58]:
x[:]

array([5, 2, 9, 3, 7])

In [59]:
x[::2]

array([5, 9, 7])

In [61]:
y[1:2, 1:]

array([[3, 5]])

In [62]:
y[0]

array([2, 4, 6])

In [63]:
y[1,1:]

array([3, 5])

In [64]:
y

array([[2, 4, 6],
       [1, 3, 5]])

In [65]:
y[:,1]

array([4, 3])

In [66]:
z = y[:,1]

In [67]:
z

array([4, 3])

In [68]:
z[1] = 1000

In [69]:
z

array([   4, 1000])

In [70]:
y

array([[   2,    4,    6],
       [   1, 1000,    5]])

In [3]:
a = np.arange(9)

In [4]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
a.shape

(9,)

In [11]:
type((9,))

tuple

In [75]:
b = np.arange(5).reshape((5,1))
b.shape

(5, 1)

In [76]:
b

array([[0],
       [1],
       [2],
       [3],
       [4]])

연산자 오버로딩과는 다르구나

In [15]:
a=np.array([1,2,3]); b=np.array([4,5,6])

In [16]:
a+b

array([5, 7, 9])

애는 어떨려나

In [17]:
c=[1,2,3]; b=[4,5,6]

In [18]:
c+b

[1, 2, 3, 4, 5, 6]

np.array()써서 리스트 만든거 연결하려면 연산해서 합쳐버리니깐 concatenate() 쓰는구나

In [87]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

In [91]:
grid1 = np.ones((3,3))

In [92]:
grid1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [93]:
grid2 = np.full((3,3), 2.)

In [94]:
grid2

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [95]:
np.concatenate([grid1,grid2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [96]:
x = np.arange(3,15,2)

In [97]:
x

array([ 3,  5,  7,  9, 11, 13])

2전까지 짜르다가 3~5전까지 짜르고 마지막에 5넣어라라는 뜻

In [100]:
a,b,c = np.split(x,[2,5])

In [101]:
a

array([3, 5])

In [102]:
b

array([ 7,  9, 11])

In [103]:
c

array([13])