In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [4]:
b = np.array([5,5,5]) #np.full 함수도 사용 가능

In [5]:
a + b

array([6, 7, 8])

In [6]:
(a+1)**2

array([ 4,  9, 16], dtype=int32)

In [7]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [8]:
np.random.seed(0)

In [9]:
x=np.random.random(10)

In [10]:
x

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [11]:
sum(x)

6.157662833145425

In [12]:
np.sum(x) # 아래와 같음

6.157662833145425

In [18]:
x.sum() # 위와 같음

6.157662833145425

#### 매직명령어

In [13]:
%time sum(np.random.random(10000))

Wall time: 1 ms


4962.657988754934

In [15]:
%timeit sum(np.random.random(10000))

607 µs ± 1.05 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [17]:
%timeit np.sum(np.random.random(10000))

45.4 µs ± 62.1 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [19]:
y = np.array([[1,2],[3,4]])

In [20]:
y

array([[1, 2],
       [3, 4]])

In [21]:
np.sum(y)

10

In [23]:
np.sum(y, axis = 0) # 각 열의 합(column sum)

array([4, 6])

In [24]:
np.sum(y, axis = 1) # 각 행의 합(low sum)

array([3, 7])

In [28]:
t = np.array([5,2,8,5,1], dtype=np.float64)

In [26]:
np.max(t)

8

In [27]:
np.argmax(t) # 최대 값 인덱스

2

In [32]:
t[0] = np.NaN #  일종의 NULL 값, Not a Number

In [33]:
t

array([nan,  2.,  8.,  5.,  1.])

In [34]:
np.sum(t)

nan

In [35]:
np.nansum(t)

16.0

In [36]:
x = np.array([4,2,6,7,3.3])

In [37]:
z = (x - np.mean(x)) / np.std(x) # 여기부터 ?

In [38]:
z

array([-0.25374507, -1.35698453,  0.84949438,  1.40111411, -0.63987888])

In [39]:
z.mean()

-4.4408920985006264e-17

In [40]:
z.std()

1.0

In [41]:
X = np.random.randint(0,100,(10,2))

In [42]:
X

array([[20, 80],
       [75, 97],
       [ 8, 54],
       [47, 70],
       [10, 34],
       [15, 83],
       [94, 47],
       [55, 18],
       [54, 51],
       [13, 42]])

In [43]:
avgs = np.mean(X, axis=0)

In [44]:
avgs

array([39.1, 57.6])

In [45]:
sds = np.std(X, axis=0)

In [46]:
sds

array([28.77655296, 23.21723498])

In [47]:
Z = (X-avgs)/sds

In [48]:
Z

array([[-0.66373481,  0.9648005 ],
       [ 1.24754344,  1.69701517],
       [-1.08074098, -0.15505722],
       [ 0.27452906,  0.53408599],
       [-1.01123995, -1.01648624],
       [-0.83748738,  1.09401486],
       [ 1.90780321, -0.45655738],
       [ 0.55253317, -1.70562946],
       [ 0.51778266, -0.28427158],
       [-0.90698841, -0.67191464]])

In [49]:
x = np.arange(7)

In [50]:
x

array([0, 1, 2, 3, 4, 5, 6])

In [51]:
x < 3

array([ True,  True,  True, False, False, False, False])

In [52]:
np.where(x<3,1,0)

array([1, 1, 1, 0, 0, 0, 0])

In [55]:
x[x<3] # 부울 마스킹

array([0, 1, 2])

In [56]:
a = np.array([[0,1],[2,3]])

In [57]:
b = np.array([[1,1],[4,0]])

In [58]:
a

array([[0, 1],
       [2, 3]])

In [59]:
b

array([[1, 1],
       [4, 0]])

In [60]:
a @ b # 행렬 곱

array([[ 4,  0],
       [14,  2]])

In [61]:
np.dot(a,b)

array([[ 4,  0],
       [14,  2]])