In [1]:
import numpy as np

In [4]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
np.random.normal(0,1,(3,3))

array([[-0.64625324,  0.56561912, -0.08432065],
       [-0.3595485 ,  0.19523207, -0.10415012],
       [ 1.82094949,  1.09352808,  0.82179102]])

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
np.empty(4)

array([1., 1., 1., 1.])

In [13]:
x=np.random.randint(10,size=6)

In [14]:
y=np.random.randint(1,6,size=(3,4))

In [15]:
x2=x[1:4]

In [16]:
x3=x[1:4].copy()

In [17]:
x2[0]=100

In [18]:
print(x)

[  9 100   8   0   4   0]


In [19]:
x3[1]=200

In [20]:
print(x)

[  9 100   8   0   4   0]


In [21]:
z=np.array([1,2,3])

In [22]:
z.reshape((1,3))

array([[1, 2, 3]])

In [23]:
z[np.newaxis,:]

array([[1, 2, 3]])

In [24]:
z[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [25]:
arr=np.arange(15).reshape((3,5))

In [26]:
arr2 = arr.T #arr.transpose()

In [27]:
arr2.shape

(5, 3)

In [28]:
arr2

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [29]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [32]:
a=np.full((2,3),1)
b=np.full((2,3),2)

In [33]:
np.r_[a,b]

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [34]:
np.c_[a,b]

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

In [38]:
x=np.array([1,2,3])

In [35]:
grid = np.array([[4,5,6],[7,8,9]])

In [36]:
np.concatenate([grid,grid])

array([[4, 5, 6],
       [7, 8, 9],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
np.concatenate([grid,grid],axis=1)

array([[4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [39]:
np.vstack([x,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
z=np.array([[99],[99]])

In [42]:
np.hstack([grid,z])

array([[ 4,  5,  6, 99],
       [ 7,  8,  9, 99]])

In [43]:
x=[1,2,3,99,99,3,2,1]
x

[1, 2, 3, 99, 99, 3, 2, 1]

In [45]:
x1,x2,x3 =np.split(x,[3,5])

In [46]:
x1

array([1, 2, 3])

In [47]:
x2

array([99, 99])

In [48]:
x3

array([3, 2, 1])

In [49]:
a=np.array([1,2,3])
b=np.array([5,5,5])

In [50]:
a+b

array([6, 7, 8])

In [51]:
(a+1)**2

array([ 4,  9, 16], dtype=int32)

In [52]:
np.add(a,b)

array([6, 7, 8])

In [55]:
np.ones((3,3))+np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [59]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [63]:
np.arange(3).reshape(3,1)+np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [64]:
np.random.random((3,3))

array([[0.94679446, 0.06434919, 0.74555909],
       [0.76455711, 0.49613424, 0.77072576],
       [0.91404669, 0.04445083, 0.85108428]])

In [65]:
x =np.array([1,2,3,4,5])

In [66]:
x<3

array([ True,  True, False, False, False])

In [68]:
(2*x) == (x**2)

array([False,  True, False, False, False])

In [3]:
x=np.arange(5)

In [4]:
np.less(x,3)

array([ True,  True,  True, False, False])

In [5]:
a=np.arange(10)

In [6]:
np.where(a<5,a,10*a)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [8]:
M=np.arange(12).reshape((3,4))

In [9]:
M

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
row=np.array([0,1,2])
col=np.array([2,1,3])

In [11]:
M[row,col]

array([ 2,  5, 11])

In [12]:
mat=[[1,2],[3,4]]

In [13]:
mat[1]

[3, 4]